#!/bin/bash

# Ensure the script is being run from the correct directory
PROJECT_DIR=$(dirname "$0")
cd "$PROJECT_DIR"

# Set the Java agent path
AGENT_JAR="./target/my-instrumentation-project-1.0-SNAPSHOT.jar"

# Set the classpath for the target application
# CLASSPATH="target/classes"

# CLASSPATH="/home/fred/javatest/target/classes"

CLASSPATH="/home/fred/Java-Snake-Game/out/"

# Set the main class to run
# MAIN_CLASS="com.example.ExampleClass"

MAIN_CLASS="com.zetcode.Snake"

# Check if the agent JAR exists
if [[ ! -f "$AGENT_JAR" ]]; then
  echo "Error: Agent JAR not found at $AGENT_JAR"
  exit 1
fi

# Check if the classes directory exists
if [[ ! -d "$CLASSPATH" ]]; then
  echo "Error: Classes directory not found at $CLASSPATH"
  exit 1
fi

# Run the Java application with the agent
# java -cp "$CLASSPATH" "$MAIN_CLASS"
java -javaagent:"$AGENT_JAR" -cp "$CLASSPATH" "$MAIN_CLASS"

# java  -javaagent:/home/fred/ece496/target/my-instrumentation-project-1.0-SNAPSHOT.jar -cp "/home/mark/pmd-bin-7.2.0/lib/*" -Xmx1024m net.sourceforge.pmd.cli.PmdCli cpd --minimum-tokens 100 --dir sfdx-scanner --format xml --language java --skip-lexical-errors

# java -cp "$CLASSPATH" "$MAIN_CLASS"
